### ISSUE TITLE
Not Working With SvelteKit

### ISSUE THREAD

**Issue by rakataprime** [dopry/svelte-auth0#40]
Hello, 

I was unable to use the component with sveltekit v 1.0.0-next.589 with svelte version 3.55.1

It looks like the auth0Promise variable is undefined when using with sveltekit.  I'm not sure exactly whats causing this behavior. 

This should be able to be reproduced by putting the demo component into a +page.svelte file in any template project.  I am also using tailwind css, but i don't think that that should matter. 

+page.svelte
```
<script lang='ts>
import {
  Auth0Context,
  Auth0LoginButton,
  Auth0LogoutButton,
  authError,
  authToken,
  idToken,
  isAuthenticated,
  isLoading, 
  login,
  logout,
  userInfo,
} from '@dopry/svelte-auth0';

</script>
<Auth0Context 
domain="***********"
client_id="*********"
audience="*********'
callback_url="********"
logout_url="*********'
>
  <Auth0LoginButton class="text-white bg-black">Login</Auth0LoginButton>
  <Auth0LogoutButton class="text-white bg-black">Logout</Auth0LogoutButton>
  <pre>isLoading: {$isLoading}</pre>
  <pre>isAuthenticated: {$isAuthenticated}</pre>
  <pre>authToken: {$authToken}</pre>
  <pre>idToken: {$idToken}</pre>
  <pre>userInfo: {JSON.stringify($userInfo, null, 2)}</pre>
  <pre>authError: {$authError}</pre>
</Auth0Context>
```

Error:
  ``` TypeError: Cannot read properties of undefined (reading 'default')
    at Auth0Context.svelte:37:23
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+page.svelte:132:97)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.default (root.svelte:41:38)
    at eval (/src/routes/+layout.svelte:21:77)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at root.svelte:40:37
    at $$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1884:26)
```

**Comment by dopry** [comment]
Is this render SSR?
